use std::process::Command;

use color_eyre::eyre::{Context, ContextCompat, Result, eyre};
use serde::{Deserialize, Serialize};

/// The review decision marked on the title page checkbox.
#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub(crate) enum ReviewDecision {
    Approve,
    RequestChanges,
    CommentOnly,
    /// No checkbox was clearly marked.
    Unclear,
}

/// A single annotation interpreted from handwriting on a diff page.
#[derive(Debug, Serialize, Deserialize)]
pub(crate) struct Annotation {
    /// The file path this annotation refers to.
    /// None if the annotation is a general comment not tied to a specific file.
    pub path: Option<String>,
    /// The line number from the margin of the section the annotation targets.
    /// If side is "left", this is the old file's line number.
    /// If side is "right", this is the new file's line number.
    /// None if the annotation is a general comment on the hunk.
    pub line: Option<usize>,
    /// Whether this targets the "Removed" (old/LEFT) or "Added" (new/RIGHT) section.
    pub side: DiffSide,
    /// The interpreted text of the handwritten annotation.
    pub body: String,
}

/// Which side of the diff an annotation targets.
#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "UPPERCASE")]
pub(crate) enum DiffSide {
    Left,
    Right,
}

/// The full interpreted review from an annotated PDF.
#[derive(Debug, Serialize, Deserialize)]
pub(crate) struct InterpretedReview {
    /// The review decision from the title page checkbox.
    pub decision: ReviewDecision,
    /// All annotations found across diff pages.
    pub annotations: Vec<Annotation>,
}

impl InterpretedReview {
    /// Returns true if the review has no annotations and no clear decision.
    pub(crate) fn is_empty(&self) -> bool {
        self.annotations.is_empty() && matches!(self.decision, ReviewDecision::Unclear)
    }
}

/// Find a JSON object in text that may contain surrounding prose or markdown.
fn extract_json_from_text(text: &str) -> Option<&str> {
    let start = text.find('{')?;
    let end = text.rfind('}')?;
    if end > start {
        Some(&text[start..=end])
    } else {
        None
    }
}

/// Extract the text content from the Claude CLI's JSON envelope.
/// The CLI with `--output-format json` returns `{"result": "...text...", ...}`.
fn extract_claude_response(raw: &str) -> Result<String> {
    let envelope: serde_json::Value =
        serde_json::from_str(raw).wrap_err("Claude CLI output is not valid JSON")?;

    // Try common envelope shapes
    if let Some(result) = envelope.get("result").and_then(|v| v.as_str()) {
        return Ok(result.to_string());
    }
    if let Some(text) = envelope.get("text").and_then(|v| v.as_str()) {
        return Ok(text.to_string());
    }
    // If the envelope itself looks like our annotation JSON, return as-is
    if envelope.get("decision").is_some() {
        return Ok(raw.to_string());
    }

    Err(eyre!(
        "unexpected Claude CLI response format: {}",
        &raw[..raw.len().min(200)]
    ))
}

const PROMPT: &str = r#"You are interpreting a handwritten code review from a PDF.

## Context

This PDF was generated by inkrement, a tool that prints GitHub PR diffs to a
reMarkable e-ink tablet for pen-based code review. The reviewer annotated the
printed diff by hand using a stylus on the tablet. All marks are deliberate pen
strokes -- there are no accidental touches. Handwriting may be imperfect; use
surrounding code context to infer intent when uncertain.

## Document structure

- **Page 1**: Title page with PR metadata and three checkboxes:
  Approve, Request Changes, Comment Only.
  Look for a handwritten check mark, X, or fill in one of the boxes.

- **Description page(s)**: The PR description rendered as text. May span
  multiple pages. The reviewer may write general comments here -- capture
  these with path and line set to null.

- **Files Changed page**: A listing of changed files. The reviewer may
  write general comments here -- capture these with path and line set to null.

- **Diff pages** (before "REFERENCE SOURCE CODE"): The core review pages.
  Each page shows:
  - A file path and hunk ID (e.g. [H1]) at the top
  - A "Removed" section showing OLD code with OLD line numbers in the left margin
  - An "Added" section showing NEW code with NEW line numbers in the left margin
  - Handwritten annotations appear between, beside, or on top of these sections

- **Pages after "REFERENCE SOURCE CODE"**: Full source files for reference.
  Ignore these pages entirely.

## What to look for

On every page before "REFERENCE SOURCE CODE", identify all handwritten annotations:
- Written text (comments, questions, suggestions, code corrections)
- Arrows pointing from a comment to a specific line of code
- Highlights, underlines, or circles around code
- Handwritten code suggesting a replacement or addition
- Crossing out / strikethrough of code lines

## For each annotation, determine:

1. **path**: The file path from the page header
2. **line**: The line number from the left margin of the section being annotated.
   - If the annotation is on the "Removed" section, this is the OLD file line number.
   - If the annotation is on the "Added" section, this is the NEW file line number.
   - Set to null if you cannot confidently identify the exact line.
3. **side**: "LEFT" if it targets the Removed (old code) section,
   "RIGHT" if it targets the Added (new code) section.
   Default to "RIGHT" if ambiguous.
4. **body**: Your best interpretation of the handwritten text.
   If the annotation is a code suggestion, format it as code.
   If it is an arrow or highlight with no text, describe what is being indicated.

## Output format

Respond with ONLY valid JSON matching this exact schema:

{
  "decision": "approve | request_changes | comment_only | unclear",
  "annotations": [
    {
      "path": "src/main.rs",
      "line": 42,
      "side": "RIGHT",
      "body": "This should validate the input first"
    },
    {
      "path": null,
      "line": null,
      "side": "RIGHT",
      "body": "General comment not tied to a specific file"
    }
  ]
}

If no checkbox is clearly marked, use "unclear".
If there are no handwritten annotations, return an empty annotations array.
"#;

/// Send an annotated PDF to Claude for OCR interpretation.
///
/// Calls the `claude` CLI as a subprocess with the PDF file,
/// parses the structured JSON response into an `InterpretedReview`.
pub(crate) fn interpret_pdf(pdf_path: &std::path::Path) -> Result<InterpretedReview> {
    let parent_dir = pdf_path
        .parent()
        .ok_or_else(|| eyre!("PDF path has no parent directory"))?;
    let file_name = pdf_path
        .file_name()
        .and_then(|n| n.to_str())
        .ok_or_else(|| eyre!("PDF path has no valid filename"))?;

    let prompt_with_file = format!("{PROMPT}\n\n@{file_name}");

    let output = Command::new("claude")
        .current_dir(parent_dir)
        .args(["-p", &prompt_with_file, "--output-format", "json"])
        .output()
        .wrap_err("failed to run claude CLI -- is it installed and authenticated?")?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(eyre!("claude CLI failed: {stderr}"));
    }

    let raw = String::from_utf8_lossy(&output.stdout);

    // The claude CLI with --output-format json wraps the response in a JSON envelope.
    // Extract the actual text content from the envelope, then parse our annotation JSON.
    let text = extract_claude_response(&raw)
        .wrap_err("failed to extract text from Claude CLI response")?;

    // Claude may include prose before/after the JSON, possibly in a markdown code block.
    // Find the JSON object by looking for the outermost { ... }.
    let json_str = extract_json_from_text(&text).wrap_err_with(|| {
        format!("could not find JSON in Claude's response.\nRaw response:\n{text}")
    })?;

    serde_json::from_str(json_str).wrap_err_with(|| {
        format!("failed to parse Claude's response as annotation JSON.\nRaw JSON:\n{json_str}")
    })
}
