use color_eyre::eyre::{Context, Result, eyre};
use lopdf::Document;

/// The marker text on the separator page that divides review content from reference source code.
const SEPARATOR_MARKER: &str = "REFERENCE SOURCE CODE";

/// Strip source pages from an annotated PDF.
///
/// Finds the separator page containing "REFERENCE SOURCE CODE" and returns
/// a new PDF containing only the pages before it. This is used to reduce
/// the content sent to Claude for OCR interpretation, since the source
/// reference pages contain no handwritten annotations.
pub(crate) fn strip_source_pages(pdf_bytes: &[u8]) -> Result<Vec<u8>> {
    let doc = Document::load_mem(pdf_bytes).wrap_err("failed to parse PDF")?;
    let separator_page = find_separator_page(&doc)?;

    // Collect page numbers to delete (separator page and everything after)
    let total_pages = doc.get_pages().len() as u32;
    let pages_to_delete: Vec<u32> = (separator_page..=total_pages).collect();

    let mut stripped = doc;
    stripped.delete_pages(&pages_to_delete);

    let mut output = Vec::new();
    stripped
        .save_to(&mut output)
        .wrap_err("failed to write stripped PDF")?;

    Ok(output)
}

/// Find the 1-based page number of the separator page.
///
/// Searches each page's text content for the SEPARATOR_MARKER string.
/// Uses lopdf's text extraction which handles compressed content streams.
fn find_separator_page(doc: &Document) -> Result<u32> {
    let pages = doc.get_pages();

    for &page_num in pages.keys() {
        // extract_text returns all text on a page as a string
        let text = doc.extract_text(&[page_num]);
        if let Ok(text) = text {
            if text.contains(SEPARATOR_MARKER) {
                return Ok(page_num);
            }
        }
    }

    Err(eyre!(
        "could not find separator page ('{}') in PDF - the PDF may not have been generated by inkrement",
        SEPARATOR_MARKER
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn separator_marker_is_ascii() {
        assert!(SEPARATOR_MARKER.is_ascii());
    }
}
